services:
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    networks:
      - app-network

  client:
    build: ./client
    container_name: client
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge